// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresupuestitoBack.DataAccess;

#nullable disable

namespace PresupuestitoBack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711213345_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PresupuestitoBack.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<int>("IdPerson")
                        .HasColumnType("INT");

                    b.HasKey("IdClient");

                    b.HasIndex("IdPerson");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("IdEmployee");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<int>("IdPerson")
                        .HasColumnType("INT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdPerson");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("IdPerson");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("IdSupplier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupplier"));

                    b.Property<int>("IdPerson")
                        .HasColumnType("INT");

                    b.HasKey("IdSupplier");

                    b.HasIndex("IdPerson");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Client", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany("Clients")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Employee", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany("Employees")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Supplier", b =>
                {
                    b.HasOne("PresupuestitoBack.Models.Person", "OPerson")
                        .WithMany("Suppliers")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OPerson");
                });

            modelBuilder.Entity("PresupuestitoBack.Models.Person", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Employees");

                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
